### ISSUE TITLE
Groups system

### ISSUE THREAD

**Issue by jonasliendl** [zwitscheronline/zwitscher-api#3]
Implement a group system where users can create groups, manage them, create groups-only posts, and more. Groups can also be private, so users have to create a join request in order to join the group.

**To-Dos**
- [x] Group Repository
- [x] Join Request repository
- [x] Group member repository
- [x] Group service
- [x] Join Requests service
- [x] Groups controller

**Comment by jonasliendl** [comment]
Done.
